#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux64
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/VLC amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /VLC/..;
                                     apt-get update;
                                     apt-get -y install sudo zip git;
                                     git clone https://github.com/omega-gg/VLC;
                                     cd VLC;
                                     sh build.sh linux;
                                     cd deploy;
                                     zip -rq ../VLC.zip *"
  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
    artifact: VLC-linux64
