#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

#- job: linux64
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker run -d --name ubuntu -v $PWD:/VLC amd64/ubuntu:18.04 tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /VLC/..;
#                                     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list;
#                                     apt-get update;
#                                     apt-get -y install sudo zip git;
#                                     git clone https://github.com/omega-gg/VLC;
#                                     cd VLC;
#                                     sh build.sh linux;
#                                     cd deploy;
#                                     zip -rq ../VLC.zip *"
#  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
#    artifact: VLC-linux64

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android32
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      git clone https://github.com/omega-gg/docker
      cd docker
      sudo sh load.sh debian-vlc-android
      sudo docker run -d --name ubuntu -v $PWD:/VLC debian-vlc-android tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /VLC;
                                     git clone https://github.com/videolan/vlc-android;
                                     cd vlc-android;
                                     sh compile.sh -r -a armeabi-v7a;
                                     cd -;
                                     zip -rq VLC.zip *"
  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
    artifact: VLC-android32
