#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

#- job: linux64
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker run -d --name ubuntu -v $PWD:/VLC amd64/ubuntu:18.04 tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /VLC/..;
#                                     sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list;
#                                     apt-get update;
#                                     apt-get -y install sudo zip git;
#                                     git clone https://github.com/omega-gg/VLC;
#                                     cd VLC;
#                                     sh build.sh linux;
#                                     cd deploy;
#                                     zip -rq ../VLC.zip *"
#  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
#    artifact: VLC-linux64

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

#- job: androidv7
#  timeoutInMinutes: 120
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      git clone https://github.com/omega-gg/docker
#      cd docker
#      sh load.sh debian-vlc-android
#      cd -
#      chmod 777 .
#      docker run -d --name ubuntu -v $PWD:/VLC debian-vlc-android tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /VLC;
#                                     git clone https://github.com/omega-gg/VLC;
#                                     cd VLC;
#                                     sh build.sh androidv7"
#      cd VLC/deploy
#      sudo zip -rq ../../VLC.zip *
#  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
#    artifact: VLC-androidv7

#- job: androidv8
#  timeoutInMinutes: 120
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      git clone https://github.com/omega-gg/docker
#      cd docker
#      sh load.sh debian-vlc-android
#      cd -
#      chmod 777 .
#      docker run -d --name ubuntu -v $PWD:/VLC debian-vlc-android tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /VLC;
#                                     git clone https://github.com/omega-gg/VLC;
#                                     cd VLC;
#                                     sh build.sh androidv8"
#      cd VLC/deploy
#      sudo zip -rq ../../VLC.zip *
#  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
#    artifact: VLC-androidv8

- job: android32
  timeoutInMinutes: 120
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      git clone https://github.com/omega-gg/docker
      cd docker
      sh load.sh debian-vlc-android
      cd -
      chmod 777 .
      docker run -d --name ubuntu -v $PWD:/VLC debian-vlc-android tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /VLC;
                                     git clone https://github.com/omega-gg/VLC;
                                     cd VLC;
                                     sh build.sh android32"
      cd VLC/deploy
      sudo zip -rq ../../VLC.zip *
  - publish: $(System.DefaultWorkingDirectory)/VLC.zip
    artifact: VLC-android32
